### ISSUE TITLE
Update the version of Sailor used

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/petstore-component-nodejs#2]
Since clients regularly use this component as a starting point, we should update to the latest version of sailor and [the latest working node/npm verson](https://support.elastic.io/support/solutions/folders/14000116125) so that clients using this as a starting point can make use of the latest language features.

**Comment by drobiazko** [comment]
Upgraded to v2.2.0.

**Comment by jhorbulyk** [comment]
And the node version?

**Comment by drobiazko** [comment]
Fixed
