### ISSUE TITLE
Update to the latest sailor API version

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/petstore-component-nodejs#3]
Current sailor version is 2.2.1.  Version referenced by this component is 2.2.0

**Comment by zubairov** [comment]
It's actually not. Currently it's 2.2.0

https://www.npmjs.com/package/elasticio-sailor-nodejs

2.2.1 is not yet published, but what would make sense is not to rely on the minor version so we should use ``2.2.x`` and not ``2.2.0``. 

I think the best way to fix is would be a pull request

**Comment by jhorbulyk** [comment]
Just published 2.2.1

**Comment by zubairov** [comment]
great, now PR please :)
