### ISSUE TITLE
Wrong in-metadata for create PET action

### ISSUE THREAD

**Issue by zubairov** [elasticio/petstore-component-nodejs#8]
Apparently Pet status is enumeration but it's not declared (or displayed) as such:

![image](https://user-images.githubusercontent.com/56208/34868604-a187a8d2-f784-11e7-967e-25f27b000c9a.png)

**Comment by hannah-bulmer** [comment]
Fixed in https://github.com/elasticio/petstore-component-nodejs/pull/14
